# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1edbkqtmtYUiIRiD5nkDPul7pevnwqGtu
"""

import random

number = random.randint(1, 10)
guess = int(input("Guess a number between 1 and 10: "))

if guess == number:
    print("Correct! You guessed the number.")
else:
    print(f"Wrong! The number was {number}.")

